config/routes.rb
Rails.application.routes.draw do
  get 'registration/new', to: 'registration#new'
  post 'registration/new', to: 'registration#sign_in'
  put 'registration/new', to: 'registration#log_out'
  post 'likes', to: 'likes#create'
  delete 'likes', to: 'likes#delete'
  root 'gossips#home'
  resources :gossips
  resources :comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
  belongs_to :comment, optional: :true
  has_many :sub_comments, class_name: 'Comment', foreign_key: 'related_comment_id', dependent: :destroy
  belongs_to :related_comment, class_name: 'Comment', optional: :true
  validates :content, presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :tags
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :content, presence: true
  validates :title, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :gossips
end

app/models/user.rb
class User < ApplicationRecord
  has_many :gossips, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find_by(is_logged: true) if !User.find_by(is_logged: true).nil?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    user = current_user
    @comment = Comment.new(content: params[:comment][:content], gossip_id: params[:comment][:gossip_id])
    if user.nil?
      redirect_to gossip_path(@comment.gossip_id), alert: 'Please log in to add a comment! 2'
    else
      @comment.user_id = user.id
      @comment.related_comment_id = params[:comment][:related_comment_id] unless params[:comment][:related_comment_id].nil?
      if @comment.save!
        redirect_to gossip_path(@comment.gossip_id), notice: 'New comment successfuly added'
      else
        render :new, alert: "Something went wrong. Comment couldn't be added"
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :user)
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def home
  end

  def new
    @gossip = Gossip.new
  end

  def create
    user = current_user
    @gossip = Gossip.new(title: params[:gossip][:title], content: params[:gossip][:content])

    if user.nil?
      redirect_to registration_new_path, alert: "Please log in to create a gossip!"
    else
      @gossip.update!(user_id: user.id)
      if @gossip.save!
        redirect_to gossip_path(@gossip.id), notice: 'New Gossip successfuly created'
      else
        redirect_to new_gossip_path, alert: "Something went wrong. Gossip couldn't be created"
      end
    end
  end

  def show
    if Gossip.where(id: params[:id]).exists?
      @gossip = Gossip.find(params[:id])
      @comment = Comment.new
      @current_user = current_user
      @like = Like.new
    else
      redirect_to root_path, alert: "Sorry, Gossip ##{params[:id]} does not exist"
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    if current_user && @gossip.user_id == current_user.id
      @gossip.update!(gossip_params)
      redirect_to gossip_path(@gossip.id)
    else
      flash[:alert] = "Only #{@gossip.user.name} can edit this comment"
      render :edit
    end

  end

  def destroy
    @gossip = Gossip.find(params[:id])
    if current_user && @gossip.user_id == current_user.id
      @gossip.destroy
      redirect_to gossips_path
    else
      flash[:alert] = "Only #{@gossip.user.name} can delete this comment"
      redirect_to gossip_path(@gossip.id)
    end
  end

  def index
    @gossips = Gossip.all
  end

  private

  def gossip_params
    params.require(:gossip).permit(:title, :content)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    like = Like.create!(user_id: params[:like][:user_id], gossip_id: params[:like][:gossip_id])
    redirect_to gossip_path(params[:like][:gossip_id]), notice: "You liked that gossip :)"
  end

  def delete
    like = Like.find_by(user_id: params[:like][:user_id], gossip_id: params[:like][:gossip_id])
    like.destroy
    redirect_to gossip_path(params[:like][:gossip_id]), alert: "You unliked that gossip :("
  end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
  def new
    @user = User.new
  end

  def sign_in
    if params[:commit] == 'Sign Up' && !create
      flash[:alert] = "Something went wrong. New user couldn't be created => #{@user.errors.full_messages}"
      redirect_to registration_new_path
    else
      log_in ? (redirect_to gossips_path) : (redirect_to registration_new_path)
    end
  end

  def log_in
    @user = User.find_by(email: params[:user][:email])
    if @user.password == params[:user][:password]
      User.all.each { |user| user.update(is_logged: user.id == @user.id) }
      flash[:success] = "You're now logged as #{@user.name}"
      true
    else
      flash[:alert] = "Log in failed, password and email don't match."
      false
    end
  end

  def create
    @user = User.new(name: params[:user][:name], email: params[:user][:email], password: params[:user][:password])
    @user.save
  end

  def log_out
    User.find_by(is_logged: true).update(is_logged: false)
    redirect_to root_path, :notice => "Logged out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/gossips/edit.html.erb
<div class="jumbotron card text-center bg-light border-primary mb-0">
    <h1 class='card-title text-primary text-capitalize font-weight-bold'>edit gossip #<%= @gossip.id%></h1>
    <p class='lead font-italic text-dark text-capitalize'>by <%= @gossip.user.name %> - <%= @gossip.created_at.strftime("%e %b %y - %H:%M:%S")%></p>
</div>

<div class="jumbotron text-center bg-primary mb-0">
  <div class="align-middle">
    <%= form_for @gossip, class: "form-group" do |f| %>
      <div class="d-flex justify-content-between align-items-center col-xs-3 col-sm-4 col-md-4 col-lg-4 col-xl-4 mb-3">
        <div>
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text bg-light text-primary" id="basic-addon1">Title</span>
            </div>
            <%= f.text_field :title, class: "form-control", placeholder: :title, disabled: true%><br>
          </div>
        </div>
        <div class="d-flex align-items-center">
          <div>
          <%= f.submit 'Edit', class: 'btn btn-outline-light btn-lg' %>
          </div>
        </div>
      </div>
      <div class='col-xs-6 col-sm-12 col-md-10 col-lg-8 col-xl-8'>
        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text bg-light text-primary">Gossip</span>
          </div>
          <%= f.text_area :content, class: "form-control", rows: "4", placeholder: :content, required: true %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/gossips/home.html.erb
<div class="center jumbotron d-flex flex-column justify-content-center">
  <h1 class='text-center font-weight-bold'>Welcome to ANOTHER Gossip Project !</h1>
  <h3 class='text-center'>
    <%= link_to "Get shiwfty", registration_new_path, class: "btn btn-lg btn-warning" %>
  </h3>
  <img src="https://fsmedia.imgix.net/1a/60/b9/76/0851/4896/8836/e73cbcbf04ee/rick-and-morty-netflixjpg.jpeg?rect=0%2C22%2C938%2C469&dpr=2&auto=format%2Ccompress&w=650">
</div>

app/views/gossips/index.html.erb
<div class='card-body border border-primary rounded m-2 p-3'>
  <h2 class="text-capitalize font-weight-bold text-dark">list of gossips</h2>
  <table class="table">
    <thead class="thead-dark">
      <tr>
      <th scope="col" class="text-info">#</th>
      <th scope="col">User</th>
      <th scope="col">Title</th>
      <th scope="col">Content</th>
      <th scope="col">Creation</th>
      <th scope="col">Last Update</th>
      <th scope="col">Link</th>
      </tr>
    </thead>
    <tbody>
      <% @gossips.each do |gossip| %>
      <tr>
        <th scope="row" class="text-info"><%= gossip.id %></th>
        <td class="text-capitalize"><%= gossip.user.name %></td>
        <td><%= gossip.title %></td>
        <td><%= gossip.content %></td>
        <td class='small'><%= gossip.created_at.strftime("%e %b %y - %H:%M:%S") %></td>
        <td class='small'><%= gossip.updated_at.strftime("%e %b %y - %H:%M:%S") %></td>
        <td>
          <span class="badge badge-danger"> <%= gossip.likes.count %> <img src="https://cdn.iconscout.com/icon/free/png-256/heart-like-love-blue-37839.png" width=15 heigth=15></span>
          <%= link_to 'Link', gossip_path(gossip.id), class: 'btn btn-success' %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <a href="<%= new_gossip_path %>" class='btn btn-primary btn-lg text-capitalize'>create a new gossip</a>
</div>

app/views/gossips/new.html.erb
<div class='card-body border border-primary rounded m-2 p-3'>
  <div class="jumbotron card text-center bg-dark">
    <h1 class='card-title text-light text-capitalize font-weight-bold'>create a brand new Gossip</h1>
    <p class='lead font-italic text-info'>Provide the requested information</p>
  </div>
  <div class="container">
   <div class="row justify-content-center">
      <div class="d-flex justify-content-between">
        <div class='col-xs-6 col-sm-10 col-md-10 col-lg-10 col-xl-10'>
          <%= form_for @gossip, class: "form-group", url: {action: :create}, method: 'POST' do |f| %>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text bg-light text-muted" id="basic-addon1">Title</span>
            </div>
            <%= f.text_field :title, class: "form-control", placeholder: "Rick on Marriage", required: true%><br>
          </div>
        </div>
        <div class="d-flex align-items-center">
          <div>
            <%= f.submit 'Submit', class: 'btn btn-outline-primary btn-lg' %>
          </div>
        </div>
      </div>
      <div class='col-xs-6 col-sm-12 col-md-10 col-lg-8 col-xl-8'>
        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text bg-light text-muted">Gossip</span>
          </div>
          <%= f.text_area :content, class: "form-control", 'aria-label': "bio", rows: "4", placeholder: "Weddings are basically funerals with cake", required: true %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/gossips/show.html.erb
<div class="jumbotron card text-center bg-primary">
  <h1 class='card-title text-light text-capitalize font-weight-bold'>gossip #<%= @gossip.id%></h1>
  <p><span class="badge badge-danger"> <%= @gossip.likes.count %> <img src="https://cdn.iconscout.com/icon/free/png-256/heart-like-love-blue-37839.png" width=15 heigth=15></span></p>
  <p class='lead font-italic text-dark text-uppercase'>by <%= @gossip.user.name %> - <%= @gossip.created_at.strftime("%e %b %y - %H:%M:%S") %></p>
  <hr class="my-4">
  <p class='lead text-light text-capitalize font-weight-bold'><%= @gossip.title%></p>
  <p class='lead text-light'><%= @gossip.content%></p>
  <div class='form-group'>
    <a href="<%= gossips_path %>" class="btn btn-primary" data-method="GET">Back To Gossips</a>
    <a href="<%= edit_gossip_path(@gossip.id) %>" class="btn btn-primary" data-method="GET">Edit</a>
    <a href="<%= gossip_path(@gossip.id) %>" class="btn btn-danger" data-confirm="The gossip will be deleted" data-method="DELETE">Delete</a>
    <% if @current_user %>
      <% if @current_user.likes.where(gossip_id: @gossip.id).count != 0 %>
        <%= link_to 'Unlike', likes_path(like: { gossip_id: @gossip.id, user_id: @current_user.id}), class: 'btn btn-success', method: 'delete' %>
      <% else %>
        <%= link_to 'Like', likes_path(like: { gossip_id: @gossip.id, user_id: @current_user.id}), class: 'btn btn-success', method: 'post' %>
      <% end %>
    <% end %>
  </div>
</div>

<div class='container'>
  <h3>Comments</h3>
  <hr>
  <div>
    <%= form_for @comment, class: "form-group" do |f| %>
      <%= f.text_field :content, class: "form-control", placeholder: "Wubba lubba dub dub", required: true%>
      <%= f.submit 'Comment', class: 'btn btn-primary' %>
      <%= f.hidden_field :gossip_id, value: @gossip.id %>
    <% end %>
  </div>
  <hr>
  <% @gossip.comments.where(related_comment_id: nil).each do |comment| %>
    <div class='card'>
      <div class='card-header'>
        <div class='row justify-content-between pr-5 pl-5'>
          <div class='card-title'><%= comment.user.name %> : </div>
          <div class='form-inline'>
          <%= form_for @comment, class: "form-group" do |f| %>
            <%= f.text_field :content, class: 'form-control' %>
            <%= f.submit 'Reply', class: 'btn btn-primary' %>
            <%= f.hidden_field :gossip_id, value: @gossip.id %>
            <%= f.hidden_field :related_comment_id, value: comment.id %>
          <% end %>
          </div>
        </div>
      </div>
      <div class='card-body'>
        <blockquote class='blockquote mb-0'>
          <p><%= comment.content %></p>
          <footer class='blockquote-footer'><%= comment.created_at.strftime("%e %b %y - %H:%M:%S") %></footer>
        </blockquote>
      </div>
      <div class='card-footer'>
        <% comment.sub_comments.each do |sub_comment| %>
          <div class='card'>
            <div class='card-body'>
                <p><%= sub_comment.content %></p>
              <blockquote class='blockquote mb-0'>
                <footer class='blockquote-footer'> by <%= sub_comment.user.name %> - <%= sub_comment.created_at.strftime("%e %b %y - %H:%M:%S") %></footer>
              </blockquote>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <br>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<% flash.each do |name, msg| %>
  <% if !flash.alert.nil? %>
    <div class= "text-center text-light bg-danger m-0">
      <%= content_tag :div, msg, class: name %>
    </div>
  <% else %>
    <div class= "text-center text-light bg-success m-0">
      <%= content_tag :div, msg, class: name %>
    </div>
  <% end %>
<% end %>

<header class='text-capitalize'>
    <nav class="navbar navbar-inverse navbar-fixed-top navbar-expand-md justify-content-between">
      <div>
        <a class="navbar-brand " href="<%= root_path %>">
          <img src="http://icons.iconarchive.com/icons/graphicloads/colorful-long-shadow/256/Home-icon.png" width="30" height="30" class="d-inline-block align-top" alt="">
          home
        </a>
        <button class="navbar-toggler navbar-dark" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls=".navbar-collapse" aria-expanded="false"     aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="<%= gossips_path %>">gossips</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= new_gossip_path %>">new gossips</a>
          </li>
        </ul>
      </div>

      <div class="navbar-nav navbar-right">
        <% if current_user %>
          <ul class="nav">
            <li class='nav-item text-light'>Hi <%= current_user.name %> !</li>
            <li class='nav-item'>
              <a href="<%= registration_new_path %>" class="" data-confirm="Are you sure?" data-method="PUT"><img src="https://www.iconsdb.com/icons/preview/soylent-red/logout-xxl.png" width="25" height="25" class="d-inline-block align-top" alt="log out"></a>
            </li>
          </ul>
        <% else %>
          <a class="text-info" href="<%= registration_new_path %>">
            <img src="http://cdn.onlinewebfonts.com/svg/img_332705.png" width="30" height="30" class="d-inline-block align-top" alt="log in">
          </a>
        <% end %>
      </div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ElGossipoProjeto</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/header', locals: {current_user: current_user} %>
    <%= yield %>
  </body>
</html>